# Generated by Django 5.1.2 on 2025-03-03 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_course_teacher'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course_teacher',
            new_name='CourseTeacher',
        ),
    ]
