# Generated by Django 5.1.2 on 2025-03-19 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_rename_course_teacher_courseteacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='session',
            field=models.CharField(default='2025-2026', max_length=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('roll_no', 'session', 'program', 'semester')},
        ),
    ]
