# Generated by Django 5.1.2 on 2025-04-06 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_enrollstudent_enrollment_no_enrollstudent_roll_no_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollstudent',
            options={'verbose_name': 'Student Enrollment', 'verbose_name_plural': 'Student Enrollments'},
        ),
        migrations.RemoveField(
            model_name='enrollstudent',
            name='enrollment_no',
        ),
        migrations.RemoveField(
            model_name='enrollstudent',
            name='roll_no',
        ),
        migrations.AlterField(
            model_name='enrollstudent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
    ]
