# Generated by Django 5.1.2 on 2025-04-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_chairperson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('faculty', 'Faculty'), ('student', 'Student'), ('chairperson', 'Chairperson')], default='student', max_length=15),
        ),
    ]
