# Generated by Django 5.1.2 on 2025-05-14 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0017_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancechangerequest',
            name='requester_type',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty')], default='faculty', max_length=10),
        ),
        migrations.AlterField(
            model_name='attendancechangerequest',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_change_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
