# Generated by Django 5.1.2 on 2025-05-24 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0020_alter_customuser_role_controller'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmitCardEligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, default=75.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.department')),
            ],
            options={
                'verbose_name': 'Admit Card Eligibility',
                'verbose_name_plural': 'Admit Card Eligibility Settings',
                'unique_together': {('department',)},
            },
        ),
    ]
