# Generated by Django 5.1.2 on 2025-05-24 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0021_admitcardeligibility'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='admitcardeligibility',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='admitcardeligibility',
            name='department',
        ),
    ]
