# Generated by Django 5.1.2 on 2025-05-24 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0023_admitcardrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admitcardeligibility',
            options={'verbose_name_plural': 'Admit Card Eligibility'},
        ),
        migrations.AddField(
            model_name='admitcardeligibility',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='admitcardeligibility',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
